# Generated by Django 5.0.7 on 2024-09-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KollaTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolla_name', models.CharField(blank=True, max_length=200, null=True)),
                ('kolla_id', models.CharField(blank=True, max_length=300, null=True)),
                ('kolla_connector_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='NewModel',
        ),
        migrations.DeleteModel(
            name='Sarfraz',
        ),
    ]
