# Generated by Django 5.0.7 on 2024-08-31 19:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateColleges',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1a11ffc7-3ca3-4742-bb8d-6b7fc25d3331'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('ranking', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f1d94ff7-43fa-4dd2-bf90-5cbe994abf1f'), editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(unique=True, upload_to='fee_structure')),
                ('department', models.CharField(max_length=300)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Universty',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0360e2d3-2c46-4541-81cf-6141f4816524'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, unique=True)),
                ('registration_number', models.CharField(max_length=300)),
                ('students', models.CharField(max_length=100000)),
                ('teacher', models.CharField(blank=True, max_length=10000, null=True)),
                ('ranking', models.CharField(blank=True, max_length=200, null=True)),
                ('departments', models.CharField(max_length=300)),
                ('labs', models.CharField(blank=True, max_length=300, null=True)),
                ('area', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.UUID('0ff5277d-0b25-42c9-b2dc-8d2e52085956'), editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12, null=True, unique=True)),
                ('id_card_number', models.CharField(blank=True, max_length=13, unique=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0e1bf7af-2057-45aa-bfaf-9352a424e5ed'), editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100, unique=True)),
                ('obtained_marks', models.CharField(max_length=100)),
                ('total_marks', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='myapp.universty')),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f674d9f2-ad93-4b19-9dcf-569d9c964bd0'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('sector', models.CharField(max_length=400)),
                ('requirenment', models.CharField(max_length=300)),
                ('affiliated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_college_industries', to='myapp.affiliatecolleges')),
                ('universty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_connection', to='myapp.universty')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a11fcf01-82eb-4f1d-ab30-905d014bfc59'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('merit', models.CharField(max_length=400)),
                ('seats', models.CharField(max_length=400)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='myapp.universty')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7f257dea-88a8-4652-b69f-2aefa0b2354b'), editable=False, primary_key=True, serialize=False)),
                ('students', models.CharField(max_length=300)),
                ('marks', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='myapp.universty')),
            ],
        ),
        migrations.AddField(
            model_name='affiliatecolleges',
            name='universty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='myapp.universty'),
        ),
    ]
