# Generated by Django 5.0.7 on 2024-09-09 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatecolleges',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2a600e4-4684-458e-9772-8b8245c4b0c6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3bf94a5-cf0a-435d-a008-c39a88274784'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a72e2ebf-a8df-4963-843f-2816e7be50e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f051dd2-6d29-47d6-9465-03c03f305165'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industries',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b9a9169-c20a-4746-8d52-58f63f3fbf26'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d44cc132-1e74-4449-95df-50af47fe0edb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universty',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00778968-1974-43d9-96ee-1ccc1d932063'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48d0d9ae-30f0-47fc-b46d-bce3c5c79098'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
