# Generated by Django 5.0.7 on 2024-09-09 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_affiliatecolleges_id_alter_college_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatecolleges',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4c39599-f273-4edf-b707-54438d144e3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2edc866-2710-41f5-89e9-dc2a2cb5abf4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59172d20-3c39-4dad-8df5-89642955d8d5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec265b5f-f9e5-4bd9-8952-917fbd2f00f4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industries',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eda7e9b3-a58c-4a52-a59e-6cc6e94c7c1b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c525dd91-691d-4045-bf06-4f4dde6c7052'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universty',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9529610-b4f7-49c3-8d59-9be88d6a37c8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2354dc3a-1a31-4c13-8869-6f95ac9c94c0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
